### ISSUE TITLE
中转管理 -端口已使用流量 更换中转地址后会被清零 

### ISSUE THREAD

**Issue by CaoFeiYu** [xiaoli123/forwordpanel#3]
现流量统计似乎与被中转ip 关联，更换被中转地址ip 会导致流量统计重算。
假如两个不同租户 中转同一ip比如nat场景  已使用流量会重复累计  显示在各用户中的已使用流量会是所有用户的流量总和

**Comment by xiaoli123** [comment]
收到, 后续会修复
